
{% set version = "2.9.4" %}

package:
  name: qscintilla2
  version: {{ version }}

source:
  url:  http://downloads.sourceforge.net/project/pyqt/QScintilla2/QScintilla-{{ version }}/QScintilla_gpl-{{ version }}.tar.gz
  sha256: 8b3a23023e9f0573caed6f9cee86f898d87b768ee15b8c211a423783a4cfa4e6

build:
  number: 0

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - python
    - pip
    - sip
    - qt
    - pyqt
  run:
    - python
    - sip
    - qt
    - pyqt

about:
  home: https://www.riverbankcomputing.com/software/qscintilla/intro
  license: GPL-3.0
  license_file: LICENSE
  summary: "Qscintilla2 editor for Qt"
  description: |
    QScintilla is a port to Qt of Neil Hodgson's Scintilla C++ editor control.
    As well as features found in standard text editing components, QScintilla includes features especially useful when editing and debugging source code. These include support for syntax styling, error indicators, code completion and call tips. The selection margin can contain markers like those used in debuggers to indicate breakpoints and the current line. Styling choices are more open than with many editors, allowing the use of proportional fonts, bold and italics, multiple foreground and background colours and multiple fonts.
  doc_url: http://pyqt.sourceforge.net/Docs/QScintilla2/annotated.html
  dev_url: https://www.riverbankcomputing.com/software/qscintilla/download

extra:
  recipe-maintainers:
    - dschreij
    - ocefpaf
